# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Columbus Malaylam Catholic Church 
tagline:          
description:      
url:            

author:
  name:           
  url:           

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:          
